dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk8
  - openjdk8
env:
  - DIR=projects-service
  - DIR=reports-service
install:
  - cd $DIR && mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - cd $DIR && mvn test -B
  
