dist: trusty
language: java
sudo: required
addons:
  sonarcloud:
    organization: "aletundo-github"
    token:
      secure: $SONAR_TOKEN
services:
  - docker
jdk:
  - oraclejdk8
  - openjdk8
env:
  - DIR=projects-service
  - DIR=reports-service
  - DIR=analyses-executor-service
  - DIR=notifications-service
  - DIR=analyses-configurator-service
  - DIR=gateway
  - DIR=config-server
  - DIR=eureka-server
before_install:
  - cd $DIR
install:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
  - mvn sonar:sonar
  - docker build --pull --cache-from discoaras/$DIR -t discoaras/$DIR:${TRAVIS_COMMIT::8} .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push discoaras/$DIR
  
