dist: trusty
language: java
sudo: false
addons:
  sonarcloud:
    organization: "aletundo-github"
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
  - openjdk8
env:
  - DIR=projects-service
  - DIR=reports-service
before_install:
  - cd $DIR
install:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
  - mvn sonar:sonar
  
