dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk8
  - openjdk8
env:
  - DIR=projects-service
  - DIR=reports-service
jobs:
  include:
    - stage: build
      script: cd $DIR && mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: test
      script: cd $DIR && mvn test -B
stages:
  - build
  - test