dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8
sudo: false
jobs:
  include:
    - stage: compile
      env:
        - DIR=projects-service
        - DIR=reports-service
      script: cd $DIR && mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: test
      env:
        - DIR=projects-service
        - DIR=reports-service
      script: cd $DIR && mvn test -B
stages:
  - compile
  - test