dist: trusty
language: java
sudo: false
jobs:
  include:
    - stage: build
      jdk:
        - oraclejdk8
        - openjdk8
      env:
        - DIR=projects-service
        - DIR=reports-service
      script: cd $DIR && mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: test
      jdk:
        - oraclejdk8
        - openjdk8
      env:
        - DIR=projects-service
        - DIR=reports-service
      script: cd $DIR && mvn test -B
stages:
  - build
  - test