version: '3.4'

services:
  analyses-executor-service:
    image: discoaras/analyses-executor-service
    environment:
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      SPRING_PROFILE: ${SPRING_PROFILE}
      SHARED_MONGODB_URI: ${SHARED_MONGODB_URI}
      DEBUG: ${DEBUG}
    volumes:
      - analyses-executor-service-data:/data
    deploy:
      restart_policy:
        condition: on-failure
  analyses-configurator-service:
    image: discoaras/analyses-configurator-service
    environment:
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      SPRING_PROFILE: ${SPRING_PROFILE}
      SHARED_MONGODB_URI: ${SHARED_MONGODB_URI}
      DEBUG: ${DEBUG}
    deploy:
      restart_policy:
        condition: on-failure
  projects-service:
    image: discoaras/projects-service
    environment:
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      SPRING_PROFILE: ${SPRING_PROFILE}
      SHARED_MONGODB_URI: ${SHARED_MONGODB_URI}
      DEBUG: ${DEBUG}
    volumes:
      - projects-service-data:/data
    deploy:
      restart_policy:
        condition: on-failure
  reports-service:
    image: discoaras/reports-service
    environment:
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      SPRING_PROFILE: ${SPRING_PROFILE}
      SHARED_MONGODB_URI: ${SHARED_MONGODB_URI}
      DEBUG: ${DEBUG}
    volumes:
      - reports-service-data:/data
    deploy:
      restart_policy:
        condition: on-failure
  notifications-service:
    image: discoaras/notifications-service
    environment:
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      SPRING_PROFILE: ${SPRING_PROFILE}
      SHARED_MONGODB_URI: ${SHARED_MONGODB_URI}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTH: ${SMTP_AUTH}
      SMTP_STARTTLS: ${SMTP_STARTTLS}
      DEBUG: ${DEBUG}
      NOTIFICATIONS_TO_ADDRESS_DEV: ${NOTIFICATIONS_TO_ADDRESS_DEV}
    deploy:
      restart_policy:
        condition: on-failure
  gateway:
    image: discoaras/gateway
    environment:
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      SPRING_PROFILE: ${SPRING_PROFILE}
      DEBUG: ${DEBUG}
      GATEWAY_PORT: ${GATEWAY_PORT}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
volumes:
  analyses-executor-service-data:
  projects-service-data:
  reports-service-data: