version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - broker-net
  kafka:
    image: wurstmeister/kafka:0.10.1.1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ADVERTISED_PORT:  ${KAFKA_ADVERTISED_PORT}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS:  ${KAFKA_TOPICS}
    restart: on-failure
    depends_on:
      - zookeeper
    networks:
      - broker-net
  config-server:
    build:
      context: config-server/
    restart: on-failure
    networks:
      - config-net
  eureka-server:
    build:
      context: eureka-server/
    restart: on-failure
    depends_on:
      - config-server
    networks:
      - config-net
      - backend-net

networks:
  config-net:
    driver: bridge
  backend-net:
    driver: bridge
  broker-net:
    driver: bridge
