version: '3.4'

services:
  config-server:
    image: discoaras/config-server
    environment:
      CONFIG_SERVER_PORT: ${CONFIG_SERVER_PORT}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      DEBUG: ${DEBUG}
    deploy:
      restart_policy:
        condition: on-failure
  zookeeper:
    image: wurstmeister/zookeeper
    deploy:
      restart_policy:
        condition: on-failure
  kafka:
    image: wurstmeister/kafka:1.1.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ADVERTISED_PORT: ${KAFKA_ADVERTISED_PORT}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_CREATE_TOPICS: ${KAFKA_TOPICS}
    deploy:
      restart_policy:
        condition: on-failure
  shared-mongodb:
    image: mongo:3.7
    volumes:
      - shared-mongodb-configdb:/data/configdb
      - shared-mongodb-db:/data/db
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  shared-mongodb-db:
  shared-mongodb-configdb: