spring:
  application:
    name: analyses-configurator-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
      bindings:
        analysis-configurations-out:
          destination: configurations
          content-type: application/json
          producer:
            headerMode: headers
  data:
    mongodb:
      uri: ${SHARED_MONGODB_URI}/analyses-configurator
server:
  port: 0
