spring:
  application:
    name: analyses-executor-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
      bindings:
        analyses-in:
          group: analysesGroup
          destination: analyses
          contentType: application/json
          consumer:
            headerMode: raw
        analyses-out:
          destination: analyses
          contentType: application/json
          producer:
            headerMode: raw
  data:
    mongodb:
      uri: "mongodb://analyses-executor-mongodb:27017/analyses-executor"
server:
  port: 0
