spring:
  application:
    name: analyses-configurator-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
      bindings:
        output:
          destination: analyses
          content-type: application/json
  data:
    mongodb:
      uri: ${SHARED_MONGODB_URI}/analyses-configurator
server:
  port: 0
