spring:
  application:
    name: analyses-executor-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
      bindings:
        analyses-in:
          group: analysesGroup
          destination: analyses
          contentType: application/json
          consumer:
            headerMode: headers
        analyses-out:
          destination: analyses
          contentType: application/json
          producer:
            headerMode: headers
  data:
    mongodb:
      uri: ${SHARED_MONGODB_URI}/analyses-executor
server:
  port: ${ANALYSES_EXECUTOR_SERVICE_PORT}
