spring:
  application:
    name: analyses-executor-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
      bindings:
        output:
          destination: analyses
          content-type: application/json
        input:
          group: analysesGroup
          destination: analyses
          content-type: application/json
      default:
        consumer:
          headerMode: raw
        producer:
          headerMode: raw
server:
  port: 0
