eureka:
  client:
    region: default
    serviceUrl:
      defaultZone: http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
spring:
  output:
    ansi:
      enabled: DETECT