spring:
  application:
    name: eureka-server
server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
