spring:
  application:
    name: gateway
zuul:
  ignored-services: "*"
  prefix: /api/v1
  routes:
    projects-service:
      path: /projects/**
      service-id: projects-service
    reports-service:
      path: /reports/**
      service-id: reports-service
    analyses-configurator-service:
      path: /configurations/**
      service-id: analyses-configurator-service    
    analyses-executor-service:
      path: /analyses/**
      service-id: analyses-executor-service
hystrixcommand:
  discovery:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 600000
server:
  port: ${GATEWAY_PORT}
