spring:
  application:
    name: gateway
zuul:
  routes:
    eureka-server:
      path: /eureka-server/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://eureka-server:${EUREKA_SERVER_PORT}
      strip-prefix: true
    eureka-server-static:
      path: /eureka/**
      url: http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
hystrixcommand:
  discovery:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 600000
server:
  port: ${GATEWAY_PORT}
