spring:
  application:
    name: notifications-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
      bindings:
        analyses-in:
          group: notificationsGroup
          destination: analyses
          contentType: application/json
          consumer:
            headerMode: raw
        notifications-out:
          destination: notifications
          contentType: application/json
          producer:
            headerMode: raw
        reports-in:
          group: notificationsGroup
          destination: reports
          contentType: application/json
          consumer:
            headerMode: raw
  data:
    mongodb:
      uri: ${SHARED_MONGODB_URI}/notifications
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH}
          starttls:
            enable: ${SMTP_STARTTLS}
server:
  port: 0
