spring:
  application:
    name: notifications-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
      bindings:
        analyses-in:
          group: notificationsGroup
          destination: analyses
          contentType: application/json
          consumer:
            headerMode: raw
        notifications-out:
          destination: notifications
          contentType: application/json
          producer:
            headerMode: raw
        reports-in:
          group: notificationsGroup
          destination: reports
          contentType: application/json
          consumer:
            headerMode: raw
  data:
    mongodb:
      uri: ${SHARED_MONGODB_URI}/notifications
server:
  port: ${NOTIFICATIONS_SERVICE_PORT}