spring:
  application:
    name: projects-service
  data:
    mongodb:
      uri: ${SHARED_MONGODB_URI}/projects
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 600MB
      location: /tmp
server:
  port: 0
